modules/admin/controllers/PhotographersController.php
<?php

namespace app\modules\admin\controllers;

use app\models\Image;
use Yii;
use app\models\Options;
use app\models\promo\OurPhotographers;
use app\models\search\OurPhotographersSearch;
use app\modules\admin\models\PhotograperOptions;
use app\modules\admin\components\AdminController;

class PhotographersController extends AdminController
{
    public function actionIndex()
    {
        $searchModel = new OurPhotographersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate()
    {
        $model_image = new Image();
        $model_photographer = new OurPhotographers();

        if ($model_image->load(Yii::$app->request->post()) && $model_image->save()) {
            $model_photographer->image_id = $model_image->id;
            if ($model_photographer->load(Yii::$app->request->post()) && $model_photographer->save()) {
                return $this->redirect(['view', 'id' => $model_photographer->id]);
            }
        }

        return $this->render('create', [
            'model_photographer' => $model_photographer,
            'model_image' => $model_image
        ]);
    }

    public function actionView($id)
    {
        $model = OurPhotographers::findOne($id);

        return $this->render('view', [
            'model' => $model
        ]);
    }

    public function actionUpdate($id)
    {
        $model_photographer = OurPhotographers::findOne($id);
        $model_image = Image::findOne($model_photographer->image_id);

        if ($model_image && $model_image->load(Yii::$app->request->post()) && $model_image->save()) {
            $model_photographer->image_id = $model_image->id;
            if ($model_photographer->load(Yii::$app->request->post()) && $model_photographer->save()) {
                return $this->redirect(['view', 'id' => $model_photographer->id]);
            }
        }

        return $this->render('update', [
            'model_photographer' => $model_photographer,
            'model_image' => $model_image
        ]);
    }

    /**
     * Редактирование заголовка и описания блока "Our photographers"
     *
     * @return string
     */
    public function actionOptions()
    {
        $option_title = Options::findByKey('promo_our_photographers_title');
        $option_description = Options::findByKey('promo_our_photographers_description');
        $option_count = Options::findByKey('promo_our_photographers_count');
        $option_button = Options::findByKey('promo_our_photographers_button');

        $model = new PhotograperOptions();

        if (Yii::$app->request->isPost && $model->load(Yii::$app->request->post())) {

            if ($option_count) {
                $option_count->value = $model->block_count;
                $option_count->save();
            }

            if ($option_title) {
                $option_title->value = $model->title;
                $option_title->save();
            }

            if ($option_description) {
                $option_description->value = $model->description;
                $option_description->save();
            }

            if ($option_button) {
                $option_button->value = $model->button_caption;
                $option_button->save();
            }
        }

        $model->block_count = $option_count ? $option_count->value : null;
        $model->title = $option_title ? $option_title->value : $option_title;
        $model->description = $option_description ? $option_description->value : null;
        $model->button_caption = $option_button ? $option_button->value : null;

        return $this->render('options', [
            'model' => $model,
        ]);
    }
}

modules/admin/controllers/UsersController.php
<?php

namespace app\modules\admin\controllers;


use Yii;
use app\modules\admin\components\AdminController;
use app\models\User;
use yii\db\Query;


/**
 * Class NumbersController
 * @package app\modules\admin\controllers
 */
class UsersController extends AdminController
{

    /**
     * Действие по умолчанию
     * @return string|\yii\web\Response
     */
    public function actionIndex()
    {
        $searchModel = new User();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
        ]);
    }

    /**
     * Действие создание
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new User(['scenario' => 'create']);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->redirect(['users/index']);
        }

        return $this->render('create', ['model' => $model]);
    }

    /**
     * Действие обновление
     * @return string|\yii\web\Response
     */
    public function actionUpdate($id)
    {
        $model = User::getModel($id);
        $model->setScenario('update');
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->redirect(['users/index']);
        }
        return $this->render('update', ['model' => $model]);
    }


    /**
     * Действие удаление
     * @return string|\yii\web\Response
     */
    public function actionDelete($id)
    {
        $model = User::getModel($id);
        $model->delete();
        $this->redirect(['users/index']);
    }

    public function actionSearch($q = null, $id = null)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $out = ['results' => ['id' => '', 'username' => '']];

        if (!is_null($q)) {
            $query = new Query;

            $query->select('id, username')
                ->from('user')
                ->where(['like', 'username', $q])
                ->limit(20);

            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        } elseif ($id > 0) {
            $out['results'] = ['id' => $id, 'username' => User::find($id)->all()->username];
        }
        return $out;
    }
}

modules/admin/views/photographers/_form.php
<?php
/**
 * Created by PhpStorm.
 * User: IF
 * Date: 05.06.2019
 * Time: 20:54
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\web\JsExpression;
use kartik\select2\Select2;
use dosamigos\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
$url = \yii\helpers\Url::to(['users/search']);
?>

<div class="photographer-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model_photographer, 'user_id')->widget(Select2::classname(), [
        'initValueText' => '',
        'model' => $model_photographer,
        'attribute' => 'username',
        'options' => ['placeholder' => 'Выберите пользователя'],
        'pluginOptions' => [
            'allowClear' => true,
            'minimumInputLength' => 3,
            'language' => [
                'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
            ],
            'ajax' => [
                'url' => $url,
                'dataType' => 'json',
                'data' => new JsExpression('function(params) { return {q:params.term}; }')
            ],
            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
            'templateResult' => new JsExpression('function(user) { return user.username; }'),
            'templateSelection' => new JsExpression('function (user) { return user.username; }'),
        ],
    ]); ?>

    <?= $form->field($model_image, 'img')->fileInput() ?>

    <?= $form->field($model_photographer, 'title')->textInput(['maxlength' => true]) ?>

    <?php echo $form->field($model_photographer, 'description')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'basic'
    ]); ?>

    <?= $form->field($model_photographer, 'dark_text')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('admin', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/photographers/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\OurPhotographersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="photographer-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'description') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/photographers/create.php
<?php
/**
 * Created by PhpStorm.
 * User: IF
 * Date: 05.06.2019
 * Time: 20:56
 */
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Lang */

$this->title = Yii::t('admin', 'Add photographer');
$this->params['breadcrumbs'][] = ['label' => 'Langs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="photographer-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model_photographer' => $model_photographer,
        'model_image' => $model_image
    ]) ?>

</div>

modules/admin/views/photographers/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;


/* @var $this yii\web\View */
/* @var $searchModel app\models\search\OurPhotographersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('admin', 'Our Photographers');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="photographer-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php  echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('admin', 'Add photographer'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
//            [
//                'attribute' => 'user_id',
//                'label' => Yii::t('admin', 'User name'),
//                'content' => function($data){
//                    return $data->user->username;
//                }
//            ],
            [
                'attribute' => 'username',
                'label' => Yii::t('admin', 'User name'),
                'value' => 'user.username'
            ],
            'title',
            'description',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

modules/admin/views/photographers/options.php
<?php
/**
 * Created by PhpStorm.
 * User: IF
 * Date: 07.06.2019
 * Time: 09:07
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\promo\OurPhotographers */

$this->title = Yii::t('admin', 'Options');
$this->params['breadcrumbs'][] = ['label' => 'our photographers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="photographer-misc">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'description')->textarea(['maxlength' => true]) ?>
    <?= $form->field($model, 'block_count')->textInput(['type' => 'number']) ?>
    <?= $form->field($model, 'button_caption')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('admin', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

modules/admin/views/photographers/update.php
<?php
/**
 * Created by PhpStorm.
 * User: IF
 * Date: 05.06.2019
 * Time: 20:56
 */

use yii\helpers\Html;
use yii\web\View;

/* @var $this yii\web\View */
/* @var $model app\models\promo\OurPhotographers */

$this->title = Yii::t('admin', 'Update photographer');
$this->params['breadcrumbs'][] = ['label' => 'Photographers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="photographer-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model_photographer' => $model_photographer,
        'model_image' => $model_image
    ]) ?>

</div>

modules/admin/views/photographers/view.php
<?php
/**
 * Created by PhpStorm.
 * User: IF
 * Date: 05.06.2019
 * Time: 20:59
 */
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\promo\OurPhotographers */

$this->title = $model->getUserName();
$this->params['breadcrumbs'][] = ['label' => 'our photographers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="photographer-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('admin', 'Show all'), ['index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('admin', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('admin', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('admin','Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>



    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'image_id',
            [
                'attribute' => 'image_id',
                'label' => 'Image',
                'value'=> $model->image->img,
                'format' => ['image',['width'=>'180']],
            ],
            'trailer_id',
            'dark_text',
            'created_at',
            'updated_at',
            'author_id',
            'updater_id',
        ],
    ]) ?>

</div>